const options = {
   airouts: 'Air Outs',
   atbats: 'At Bats',
   atbatsperhomerun: 'At Bats per HR',
   avg: 'Batting Average',
   babip: 'BABIP',
   baseonballs: 'Walks',
   catchersinterference: "Catcher's Interference",
   caughtstealing: 'Caught Stealing',
   doubles: 'Doubles',
   gamesplayed: 'Games Played',
   groundintodoubleplay: 'Grounded Into Double Play',
   groundouts: 'Groundouts',
   hitbypitch: 'Hit by Pitch',
   hits: 'Hits',
   homeruns: 'Homeruns',
   intentionalwalks: 'Intentional Walks',
   leftonbase: 'Left on Base',
   numberofpitches: 'Number of Pitches Seen',
   obp: 'OBP',
   ops: 'OPS',
   plateappearances: 'Plate Appearances',
   rbi: 'RBIs',
   runs: 'Runs',
   sacbunts: 'Sac Bunts',
   sacflies: 'Sac Flies',
   slg: 'SLG',
   stolenbasepercentage: 'Stolen Base Percentage',
   stolenbases: 'Stolen Bases',
   strikeouts: 'Strikeouts',
   totalbases: 'Total Bases',
   triples: 'Triples',
}

export default options
