const options = {
   'Air Outs': 'airouts',
   'At Bats': 'atbats',
   'At Bats per HR': 'atbatsperhomerun',
   'Batting Average': 'avg',
   BABIP: 'babip',
   Walks: 'baseonballs',
   "Catcher's Interference": 'catchersinterference',
   'Caught Stealing': 'caughtstealing',
   Doubles: 'doubles',
   'Games Played': 'gamesplayed',
   'Grounded Into Double Play': 'groundintodoubleplay',
   'Grouded Into Triple Play': 'groundintotripleplay',
   Groundouts: 'groundouts',
   'Hit by Pitch': 'hitbypitch',
   Hits: 'hits',
   Homeruns: 'homeruns',
   'Intentional Walks': 'intentionalwalks',
   'Left on Base': 'leftonbase',
   'Number of Pitches Seen': 'numberofpitches',
   OBP: 'obp',
   OPS: 'ops',
   'Plate Appearances': 'plateappearances',
   RBIs: 'rbi',
   Runs: 'runs',
   'Sac Bunts': 'sacbunts',
   'Sac Flies': 'sacflies',
   SLG: 'slg',
   'Stolen Base Percentage': 'stolenbasepercentage',
   'Stolen Bases': 'stolenbases',
   Strikeouts: 'strikeouts',
   'Total Bases': 'totalbases',
   Triples: 'triples',
}

export default options
