export const pitcherOptions = {
   atbats: 'At Bats',
   avg: 'Batting Average',
   balks: 'Balks',
   baseonballs: 'Bases on Balls',
   battersfaced: 'Batters Faced',
   blownsaves: 'Blown Saves',
   catchersinterference: "Catcher's Interference",
   caughtstealing: 'Caught Stealing',
   completegames: 'Complete Games',
   doubles: 'Doubles',
   earnedruns: 'Earned Runs',
   era: 'Earned Run Average',
   gamesfinished: 'Games Finished',
   gamespitched: 'Games Pitched',
   gamesplayed: 'Games Played',
   gamesstarted: 'Games Started',
   groundintodoubleplay: 'Ground into Double Play',
   groundouts: 'Groundouts',
   groundoutstoairouts: 'Groundouts to Air Outs Ratio',
   hitbatsmen: 'Hit Batsmen',
   hitbypitch: 'Hit By Pitch',
   hits: 'Hits',
   hitsper9inn: 'Hits per 9 Innings',
   holds: 'Holds',
   homeruns: 'Home Runs',
   homerunsper9: 'Home Runs per 9 Innings',
   inheritedrunners: 'Inherited Runners',
   inheritedrunnersscored: 'Inherited Runners Scored',
   inningspitched: 'Innings Pitched',
   intentionalwalks: 'Intentional Walks',
   losses: 'Losses',
   numberofpitches: 'Number of Pitches',
   obp: 'On-Base Percentage',
   ops: 'On-Base Plus Slugging Percentage',
   outs: 'Outs',
   pickoffs: 'Pickoffs',
   pitchesperinning: 'Pitches per Inning',
   runs: 'Runs',
   runsscoredper9: 'Runs Scored per 9 Innings',
   sacbunts: 'Sacrifice Bunts',
   sacflies: 'Sacrifice Flies',
   saveopportunities: 'Save Opportunities',
   saves: 'Saves',
   shutouts: 'Shutouts',
   slg: 'Slugging Percentage',
   stolenbases: 'Stolen Bases',
   strikeouts: 'Strikeouts',
   strikeoutsper9inn: 'Strikeouts per 9 Innings',
   strikeoutwalkratio: 'Strikeout-to-Walk Ratio',
   strikepercentage: 'Strike Percentage',
   strikes: 'Strikes',
   totalbases: 'Total Bases',
   triples: 'Triples',
   walksper9inn: 'Walks per 9 Innings',
   whip: 'Walks and Hits per Inning Pitched',
   wildpitches: 'Wild Pitches',
   wins: 'Wins',
}
