export const pitcherOptions = {
   'Air Outs': 'airouts',
   'At Bats': 'atbats',
   'Batting Average': 'avg',
   Balks: 'balks',
   Balls: 'balls',
   'Bases on Balls': 'baseonballs',
   'Batters Faced': 'battersfaced',
   'Blown Saves': 'blownsaves',
   "Catcher's Interference": 'catchersinterference',
   'Caught Stealing': 'caughtstealing',
   'Complete Games': 'completegames',
   Doubles: 'doubles',
   'Earned Runs': 'earnedruns',
   'Earned Run Average': 'era',
   'Games Finished': 'gamesfinished',
   'Games Pitched': 'gamespitched',
   'Games Played': 'gamesplayed',
   'Games Started': 'gamesstarted',
   'Ground into Double Play': 'groundintodoubleplay',
   Groundouts: 'groundouts',
   'Groundouts to Air Outs Ratio': 'groundoutstoairouts',
   'Hit Batsmen': 'hitbatsmen',
   'Hit By Pitch': 'hitbypitch',
   Hits: 'hits',
   'Hits per 9 Innings': 'hitsper9inn',
   Holds: 'holds',
   'Home Runs': 'homeruns',
   'Home Runs per 9 Innings': 'homerunsper9',
   'Inherited Runners': 'inheritedrunners',
   'Inherited Runners Scored': 'inheritedrunnersscored',
   'Innings Pitched': 'inningspitched',
   'Intentional Walks': 'intentionalwalks',
   Losses: 'losses',
   'Number of Pitches': 'numberofpitches',
   'On-Base Percentage': 'obp',
   'On-Base Plus Slugging Percentage': 'ops',
   Outs: 'outs',
   'Outs Pitched': 'outspitched',
   Pickoffs: 'pickoffs',
   'Pitches per Inning': 'pitchesperinning',
   'Runs Batted In': 'rbi',
   Runs: 'runs',
   'Runs Scored per 9 Innings': 'runsscoredper9',
   'Sacrifice Bunts': 'sacbunts',
   'Sacrifice Flies': 'sacflies',
   'Save Opportunities': 'saveopportunities',
   Saves: 'saves',
   Shutouts: 'shutouts',
   'Slugging Percentage': 'slg',
   'Stolen Base Percentage': 'stolenbasepercentage',
   'Stolen Bases': 'stolenbases',
   Strikeouts: 'strikeouts',
   'Strikeouts per 9 Innings': 'strikeoutsper9inn',
   'Strikeout-to-Walk Ratio': 'strikeoutwalkratio',
   'Strike Percentage': 'strikepercentage',
   Strikes: 'strikes',
   'Total Bases': 'totalbases',
   Triples: 'triples',
   'Walks per 9 Innings': 'walksper9inn',
   'Walks and Hits per Inning Pitched': 'whip',
   'Wild Pitches': 'wildpitches',
   'Win Percentage': 'winpercentage',
   Wins: 'wins',
}
